[package]
name = "exec"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
anyhow = "1"
thiserror = "2"

tokio = "1"
tracing = "0"
tracing-subscriber = "0"

serde = "1"
serde_json = "1"

ndlibr = { path = "../" }
